baseurl      = "https://quixten.github.io"
title        = ""
languageCode = "ja"
theme        = "hello-friend-ng"
publishDir   = "docs"

[pagination]
pageSize = 10

[markup.goldmark.renderer]
  unsafe= true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "くいくすです。人間です。"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "“To live is to war with trolls in heart and soul. To write is to sit in judgement on oneself.” ― Henrik Ibsen"
  keywords = "homepage, blog"
  images = [""]

# [taxonomies]
#     category = "blog"
#     tag      = "tags"
#     series   = "series"

[languages]
  [languages.en]
    title = "どうも"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    [languages.en.params]
      subtitle = ""
      keywords = ""
      readOtherPosts = "Read other posts"
    [languages.en.params.logo]
      logoText = "quixten.github.io"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = ""
    name       = ""
    url        = ""

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/9u19su"

  [[params.social]]
    name = "twitch"
    url  = "https://twitch.tv/quix_9u19su"

  [[params.social]]
    name = "mastodon"
    url  = "https://tech.lgbt/@quix"

  [[params.social]]
    name = "pixiv"
    url  = "https://www.pixiv.net/en/users/13272918"
